<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>cloud.charging.open.protocols.WWCP.node</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Hermod\Hermod\Hermod.csproj" />
    <ProjectReference Include="..\..\Norn\Norn\Norn.csproj" />
    <ProjectReference Include="..\..\Styx\Styx\Styx.csproj" />
    <ProjectReference Include="..\..\Urdr\Urdr\Urdr.csproj" />
  </ItemGroup>

</Project>
